name: "Run Unittests via tox"
description: "Setup Python environment and run tests using tox."
runs:
  using: "composite"
  steps:
    - name: Setup standard environment
      uses: Somerandomguy10111/devops/actions/basepy@main
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/Somerandomguy10111/devops
      shell: bash
    - name: Run tox tests
      run: |
        toxtests
      shell: bash
