[project]
name = "toxlauncher"
version = "0.1.0"
authors = [{name = "Daniel Hollarek", email = "daniel.hollarek@googlemail.com"}]
description = "Launches tox tests"
readme = "readme.md"
dependencies = ['tox']

[tool.setuptools.packages.find]
include = ["toxlauncher*"]

[project.scripts]
tests = "toxlauncher.toxtests:main"

[tool.setuptools.package-data]
"toxlauncher" = ["*"]