name: "Run deptry"
description: "Setup Python environment and run deptry . to check for dependency issues"
inputs:
  python-version:
    description: "Python version to setup"
    required: true
    default: "3.11"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install deptry
      shell: bash
    - name: Run tox tests
      run: |
        dirpath=$(pwd)
        deptry $(dirpath)
      shell: bash
