name: "Run Unittests via tox"
description: "Setup Python environment and run tests using tox."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
      shell: bash
    - name: Run tox tests
      run: |
        dirpath=$(pwd)
        TOX_FILE=$(find . -name tox.ini)
        if [ -z "$TOX_FILE" ]; then
          echo "No tox.ini file found. Exiting."
          exit 1
        fi
        echo "-> Located tox file at $TOX_FILE"

        package_file=$(find "$dirpath" -maxdepth 1 \( -name "pyproject.toml" -o -name "setup.py" -o -name "setup.cfg" \) -print -quit)
        if [ -f "$package_file" ]; then
          file_name=$(basename "$package_file")
          echo "-> Found $file_name, using tox.ini with pkg environment"
          tox -c "$TOX_FILE" -e pkg $1
        elif [ -f "requirements.txt" ]; then
            echo "-> Found requirements.txt, using tox.ini with requirements environment"
            tox -c $TOX_FILE -e req
        else
            echo "Neither pyproject.toml, nor setup.py nor requirements.txt found. Nothing to test."
            exit 0
        fi
      shell: bash
